**Syllabus-Numpy**

**Introduction to Numpy, Numpy array, array, data type object, creating Numpy array, array manipulation, Array operations, reshaping, indexing, Arithmetic operations Linear algebra numpy, Random data handling, NumPy ufuncs | Universal functions**

**Numpy**

NumPy is a general-purpose array-processing Python library which provides handy methods/functions for working n-dimensional arrays.
NumPy is a short form for “Numerical Python“.
It provides various computing tools such as comprehensive mathematical functions, and linear algebra routines.

NumPy provides both the flexibility of Python and the speed of well-optimized compiled C code.

Its easy-to-use syntax makes it highly accessible and productive for programmers from any background.


In [ ]:
#Installation of Numpy Using PIP

!pip install numpy

***Array creation using List :***

In [ ]:
# Python program to create
# an array

# Creating an array using list
arr=[1, 2, 3, 4, 5]
arr

[1, 2, 3, 4, 5]

In [ ]:
arr = [1, 2, 3, 4, 5]
arr1 = ["geeks", "for", "geeks"]

**Array creation using numpy methods**
NumPy offers several functions to create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation. For example: np.zeros,np.empty etc.


In [ ]:
# Python Programming illustrating
# numpy.empty method

import numpy as g

b = g.empty(2, dtype = int)
print("Matrix b : \n", b)

a = g.empty([2, 2], dtype = int)
print("\nMatrix a : \n", a)

c = g.empty([3, 3])
print("\nMatrix c : \n", c)

Matrix b : 
 [                1 72339069014704128]

Matrix a : 
 [[10 20]
 [30 40]]

Matrix c : 
 [[ 1.54  2.99  3.42]
 [ 4.87  6.94  8.21]
 [ 7.65 10.5  77.5 ]]


In [ ]:
# Python Program illustrating
# numpy.zeros method

import numpy as g

b = g.zeros(2, dtype = int)
print("Matrix b : \n", b)

a = geek.zeros([2, 2], dtype = int)
print("\nMatrix a : \n", a)

c = g.zeros([3, 3])
print("\nMatrix c : \n", c)

Matrix b : 
 [0 0]

Matrix a : 
 [[0 0]
 [0 0]]

Matrix c : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


**numpy.arange() in Python**
Returns an array with evenly spaced elements as per the interval. The interval mentioned is half-opened i.e. [Start, Stop)

In [ ]:
# Python Programming illustrating
# numpy.arange method

import numpy as geek

print("A\n", g.arange(4).reshape(2, 2), "\n")
print("A\n", g.arange(4, 10), "\n")
print("A\n", g.arange(4, 20, 1), "\n")


A
 [[0 1]
 [2 3]] 

A
 [4 5 6 7 8 9] 

A
 [ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] 



**numpy.zeros() in Python**
The numpy.zeros() function returns a new array of given shape and type, with zeros.

In [ ]:
# Python Program illustrating
# numpy.zeros method

import numpy as g

# manipulation with data-types
b = g.zeros((2,), dtype=[('x', 'float'), ('y', 'int')])
print(b)


[(0., 0) (0., 0)]


**numpy.eye() in Python**
The eye tool returns a 2-D array with  1’s as the diagonal and  0’s elsewhere. The diagonal can be main, upper, or lower depending on the optional parameter k. A positive k is for the upper diagonal, a negative k is for the lower, and a  0 k (default) is for the main diagonal.

In [ ]:
# Python Programming illustrating
# numpy.eye method

import numpy as g

# 2x2 matrix with 1's on main diagonal
b = g.eye(2, dtype = int)
print("Matrix b : \n", b)

# matrix with R=4 C=5 and 1 on diagonal
# below main diagonal
a = g.eye(4, 5, k = 2)
print("\nMatrix a : \n", a)


Matrix b : 
 [[1 0]
 [0 1]]

Matrix a : 
 [[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


**How to Copy NumPy array into another array?**

In [ ]:
# importing Numpy package
import numpy as np

# Creating a numpy array using np.array()
org_array = np.array([1.54, 2.99, 3.42, 4.87, 6.94,
					8.21, 7.65, 10.50, 77.5])

print("Original array: ")

# printing the Numpy array
print(org_array)

# Now copying the org_array to copy_array
# using np.copy() function
copy_array = np.copy(org_array)

print("\nCopied array: ")

# printing the copied Numpy array
print(copy_array)


Original array: 
[ 1.54  2.99  3.42  4.87  6.94  8.21  7.65 10.5  77.5 ]

Copied array: 
[ 1.54  2.99  3.42  4.87  6.94  8.21  7.65 10.5  77.5 ]


**numpy.hstack() in Python**
function is used to stack the sequence of input arrays horizontally (i.e. column wise) to make a single array.

In [ ]:
# Python program explaining
# hstack() function

import numpy as g

# input array
in_arr1 = g.array([ 1, 2, 3] )
print ("1st Input array : \n", in_arr1)

in_arr2 = g.array([ 4, 5, 6] )
print ("2nd Input array : \n", in_arr2)

# Stacking the two arrays horizontally
out_arr = g.hstack((in_arr1, in_arr2))
print ("Output horizontally stacked array:\n ", out_arr)


1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output horizontally stacked array:
  [1 2 3 4 5 6]


**numpy.vstack() in python**
 function is used to stack the sequence of input arrays vertically to make a single array.

In [ ]:
# Python program explaining
# vstack() function

import numpy as g

# input array
in_arr1 = g.array([ 1, 2, 3] )
print ("1st Input array : \n", in_arr1)

in_arr2 = geek.array([ 4, 5, 6] )
print ("2nd Input array : \n", in_arr2)

# Stacking the two arrays vertically
out_arr = g.vstack((in_arr1, in_arr2))
print ("Output vertically stacked array:\n ", out_arr)


1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output vertically stacked array:
  [[1 2 3]
 [4 5 6]]


**Joining NumPy Array**


In [ ]:
import numpy as np

array_1 = np.array([1, 2])
array_2 = np.array([3, 4])

array_new = np.concatenate((array_1, array_2))
print(array_new)


[1 2 3 4]


**numpy.block()numpy.block is used to create nd-arrays from nested blocks of lists.**

In [ ]:
import numpy as np

block_1 = np.array([[1, 1], [1, 1]])
block_2 = np.array([[2, 2, 2], [2, 2, 2]])
block_3 = np.array([[3, 3], [3, 3], [3, 3]])
block_4 = np.array([[4, 4, 4], [4, 4, 4], [4, 4, 4]])

block_new = np.block([
	[block_1, block_2],
	[block_3, block_4]
])

print(block_new)


[[1 1 2 2 2]
 [1 1 2 2 2]
 [3 3 4 4 4]
 [3 3 4 4 4]
 [3 3 4 4 4]]


**Find the union of two NumPy arrays**

In [ ]:
# import libraries
import numpy as np


arr1 = np.array([10, 20, 30, 40])
print("array1 ", arr1)

arr2 = np.array([20, 40, 60, 80])
print("array2 ", arr2)

# print union of the two arrays
print("Union of two arrays :", np.union1d(arr1, arr2))


array1  [10 20 30 40]
array2  [20 40 60 80]
Union of two arrays : [10 20 30 40 60 80]


**Find unique rows in a NumPy array**

In [ ]:
# import library
import numpy as np

# Create a 2D numpy array
arr2D = np.array([[11, 11, 12, 11],
					[13, 11, 12, 11],
					[16, 11, 12, 11],
					[11, 11, 12, 11]])

print('Original Array :' ,
	arr2D, sep = '\n')

uniqueRows = np.unique(arr2D)


# print the output result
print('Unique Rows:',
	uniqueRows, sep = '\n')


Original Array :
[[11 11 12 11]
 [13 11 12 11]
 [16 11 12 11]
 [11 11 12 11]]
Unique Rows:
[11 12 13 16]


In [ ]:
#Python | Numpy np.unique() method
# import numpy
import numpy as np

a = [1, 2, 2, 4, 3, 6, 4, 8]

# using np.unique() method
gfg = np.unique(a)

print(gfg)


[1 2 3 4 6 8]


In [ ]:
# import numpy
import numpy as np

a = [[10.2, 21.4, 3.6, 14.8], [1.0, 5.0, 10.0, 15.0]]

# using np.unique() method
gfg = np.unique(a)

print(gfg)


[ 1.   3.6  5.  10.  10.2 14.8 15.  21.4]


**numpy.trim_zeros() in Python**
numpy.trim_zeros function is used to trim the leading and/or trailing zeros from a 1-D array or sequence.

In [ ]:
import numpy as g

gfg = g.array((0, 0, 0, 0, 1, 5, 7, 0, 6, 2, 9, 0, 10, 0, 0))

# without trim parameter
# returns an array without leading and trailing zeros

res = g.trim_zeros(gfg)
print(res)


[ 1  5  7  0  6  2  9  0 10]


**Numpy dstack() method**
With the help of numpy.dstack() method, we can get the combined array index by index and store like a stack by using numpy.dstack() method.

In [ ]:
# import numpy
import numpy as np

gfg1 = np.array([1, 2, 3])
gfg2 = np.array([4, 5, 6])

# using numpy.dstack() method
print(np.dstack((gfg1, gfg2)))


[[[1 4]
  [2 5]
  [3 6]]]


**Matrix manipulation in Python**
In python matrix can be implemented as 2D list or 2D Array. Forming matrix from latter, gives the additional functionalities for performing various operations in matrix. These operations and array are defines in module “numpy“.

Operation on Matrix :

1. add() :- This function is used to perform element wise matrix addition.
2. subtract() :- This function is used to perform element wise matrix subtraction.
3. divide() :- This function is used to perform element wise matrix division.

In [ ]:
# Python code to demonstrate matrix operations
# add(), subtract() and divide()

# importing numpy for matrix operations
import numpy

# initializing matrices
x = numpy.array([[1, 2], [4, 5]])
y = numpy.array([[7, 8], [9, 10]])

# using add() to add matrices
print ("The element wise addition of matrix is : ")
print (numpy.add(x,y))

# using subtract() to subtract matrices
print ("The element wise subtraction of matrix is : ")
print (numpy.subtract(x,y))

# using divide() to divide matrices
print ("The element wise division of matrix is : ")
print (numpy.divide(x,y))


The element wise addition of matrix is : 
[[ 8 10]
 [13 15]]
The element wise subtraction of matrix is : 
[[-6 -6]
 [-5 -5]]
The element wise division of matrix is : 
[[0.14285714 0.25      ]
 [0.44444444 0.5       ]]


In [ ]:
# Python code to demonstrate matrix operations
# multiply() and dot()

# importing numpy for matrix operations
import numpy

# initializing matrices
x = numpy.array([[1, 2], [4, 5]])
y = numpy.array([[7, 8], [9, 10]])

# using multiply() to multiply matrices element wise
print ("The element wise multiplication of matrix is : ")
print (numpy.multiply(x,y))

# using dot() to multiply matrices
print ("The product of matrices is : ")
print (numpy.dot(x,y))


The element wise multiplication of matrix is : 
[[ 7 16]
 [36 50]]
The product of matrices is : 
[[25 28]
 [73 82]]


In [ ]:
# Python code to demonstrate matrix operations
# sqrt(), sum() and "T"

# importing numpy for matrix operations
import numpy

# initializing matrices
x = numpy.array([[1, 2], [4, 5]])
y = numpy.array([[7, 8], [9, 10]])

# using sqrt() to print the square root of matrix
print ("The element wise square root is : ")
print (numpy.sqrt(x))

# using sum() to print summation of all elements of matrix
print ("The summation of all matrix element is : ")
print (numpy.sum(y))

# using sum(axis=0) print summation of each column of matrix
print ("The column wise summation of all matrix is : ")
print (numpy.sum(y,axis=0))

# using sum(axis=1) print summation of each row of matrix
print ("The row wise summation of all matrix is : ")
print (numpy.sum(y,axis=1))

# using "T" to transpose the matrix
print ("The transpose of given matrix is : ")
print (x.T)


The element wise square root is : 
[[1.         1.41421356]
 [2.         2.23606798]]
The summation of all matrix element is : 
34
The column wise summation of all matrix is : 
[16 18]
The row wise summation of all matrix is : 
[15 19]
The transpose of given matrix is : 
[[1 4]
 [2 5]]


**Approach: Questions**
Define matrices A and B.
Get the number of rows and columns of the matrices using the len() function.
Initialize matrices C, D, and E with zeros using nested loops or list comprehension.
Use nested loops or list comprehension to perform the element-wise addition, subtraction, and division of matrices.
Print the resulting matrices C, D, and E.

In [ ]:
A = [[1,2],[4,5]]
B = [[7,8],[9,10]]
rows = len(A)
cols = len(A[0])

# Element wise addition
C = [[0 for i in range(cols)] for j in range(rows)]
for i in range(rows):
    for j in range(cols):
        C[i][j] = A[i][j] + B[i][j]
print("Addition of matrices: \n", C)

# Element wise subtraction
D = [[0 for i in range(cols)] for j in range(rows)]
for i in range(rows):
    for j in range(cols):
        D[i][j] = A[i][j] - B[i][j]
print("Subtraction of matrices: \n", D)

# Element wise division
E = [[0 for i in range(cols)] for j in range(rows)]
for i in range(rows):
    for j in range(cols):
        E[i][j] = A[i][j] / B[i][j]
print("Division of matrices: \n", E)


Addition of matrices: 
 [[8, 10], [13, 15]]
Subtraction of matrices: 
 [[-6, -6], [-5, -5]]
Division of matrices: 
 [[0.14285714285714285, 0.25], [0.4444444444444444, 0.5]]


**empty() function**
numpy.matlib.empty() is another function for doing matrix operations in numpy.It returns a new matrix of given shape and type, without initializing entries.

In [ ]:
# Python program explaining
# numpy.matlib.empty() function

# importing numpy and matrix library
import numpy as geek
import numpy.matlib

# desired output matrix
out_mat = geek.matlib.empty((2, 3))
print ("Output matrix : ", out_mat)


Output matrix :  [[4.9e-324 2.0e-323 9.9e-324]
 [2.5e-323 1.5e-323 3.0e-323]]


** zeros() function**

numpy.matlib.zeros() is another function for doing matrix operations in numpy. It returns a matrix of given shape and type, filled with zeros.

In [ ]:
# Python program explaining
# numpy.matlib.zeros() function

# importing matrix library from numpy
import numpy as geek
import numpy.matlib

# desired 3 x 4 zero output matrix
out_mat = geek.matlib.zeros((3, 4))
print ("Output matrix : ", out_mat)


Output matrix :  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**ones() function**
numpy.matlib.ones() is another function for doing matrix operations in numpy. It returns a matrix of given shape and type, filled with ones.

In [ ]:
# Python program explaining
# numpy.matlib.ones() function

# importing matrix library from numpy
import numpy as g
import numpy.matlib

# desired 3 x 4 output matrix
out_mat = geek.matlib.ones((3, 4))
print ("Output matrix : ", out_mat)


Output matrix :  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


**numpy matrix operations | eye() function**
numpy.matlib.eye() is another function for doing matrix operations in numpy. It returns a matrix with ones on the diagonal and zeros elsewhere.

In [ ]:
# Python program explaining
# numpy.matlib.eye() function

# importing matrix library from numpy
import numpy as geek
import numpy.matlib

# desired 3 x 3 output matrix
out_mat = geek.matlib.eye(3, k = 0)
print ("Output matrix : ", out_mat)


Output matrix :  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**numpy matrix operations | identity() function**

In [ ]:
# Python program explaining
# numpy.matlib.identity() function

# importing matrix library from numpy
import numpy as geek
import numpy.matlib

# desired 3 x 3 output square identity matrix
out_mat = geek.matlib.identity(3)
print ("Output matrix : ", out_mat)


Output matrix :  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**Adding and Subtracting Matrices in Python**


In [ ]:
# importing numpy as np
import numpy as np


# creating first matrix
A = np.array([[1, 2], [3, 4]])

# creating second matrix
B = np.array([[4, 5], [6, 7]])

print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)

# adding two matrix
print("Addition of two matrix")
print(np.add(A, B))


Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Addition of two matrix
[[ 5  7]
 [ 9 11]]


In [ ]:
#Subtracting elements of matrices
# importing numpy as np
import numpy as np


# creating first matrix
A = np.array([[1, 2], [3, 4]])

# creating second matrix
B = np.array([[4, 5], [6, 7]])

print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)

# subtracting two matrix
print("Subtraction of two matrix")
print(np.subtract(A, B))


Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Subtraction of two matrix
[[-3 -3]
 [-3 -3]]


**The given task is to subtract two matrices in Python and print their elements. Approach 2 uses nested loops to subtract the two matrices. It prints the elements of both matrices using nested loops and then subtracts the corresponding elements of the matrices to get the result matrix.**

1. Define two matrices matrix1 and matrix2.
2.Print the elements of matrix1 and matrix2 using nested loops.
3. Define an empty matrix result of the same size as matrix1.
4. Subtract the corresponding elements of matrix1 and matrix2 using nested loops and store the result in the result matrix.
5. Print the result matrix.

In [ ]:
# Input matrices
matrix1 = [[1, 2], [3, 4]]
matrix2 = [[4, 5], [6, 7]]

# Printing elements of matrix1
print("Printing elements of first matrix")
for row in matrix1:
	for element in row:
		print(element, end=" ")
	print()

# Printing elements of matrix2
print("Printing elements of second matrix")
for row in matrix2:
	for element in row:
		print(element, end=" ")
	print()

# Subtracting two matrices
result = [[0, 0], [0, 0]]
for i in range(len(matrix1)):
	for j in range(len(matrix1[0])):
		result[i][j] = matrix1[i][j] - matrix2[i][j]

# Printing the result
print("Subtraction of two matrix")
for row in result:
	for element in row:
		print(element, end=" ")
	print()


Printing elements of first matrix
1 2 
3 4 
Printing elements of second matrix
4 5 
6 7 
Subtraction of two matrix
-3 -3 
-3 -3 


**Python Program to Add Two Matrices**

In [ ]:
# Program to add two matrices using nested loop

X = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[9,8,7],
    [6,5,4],
    [3,2,1]]


result = [[0,0,0],
        [0,0,0],
        [0,0,0]]

# iterate through rows
for i in range(len(X)):
# iterate through columns
    for j in range(len(X[0])):
        result[i][j] = X[i][j] + Y[i][j]

for r in result:
    print(r)


[10, 10, 10]
[10, 10, 10]
[10, 10, 10]


In [ ]:


# Program to multiply two matrices (vectorized implementation)
import numpy as np
# take a 3x3 matrix
A = [[12, 7, 3],
    [4, 5, 6],
    [7, 8, 9]]

# take a 3x4 matrix
B = [[5, 8, 1, 2],
    [6, 7, 3, 0],
    [4, 5, 9, 1]]

# result will be 3x4

result= [[0,0,0,0],
        [0,0,0,0],
        [0,0,0,0]]

result = np.dot(A,B)

for r in result:
    print(r)


[114 160  60  27]
[74 97 73 14]
[119 157 112  23]


**Python | Matrix Product**

In [ ]:
# Python3 code to demonstrate
# Matrix Product
# Using list comprehension + loop

# getting Product


def prod(val):
	res = 1
	for ele in val:
		res *= ele
	return res


# initializing list
test_list = [[1, 4, 5], [7, 3], [4], [46, 7, 3]]

# printing original list
print("The original list : " + str(test_list))

# using list comprehension + loop
# Matrix Product
res = prod([ele for sub in test_list for ele in sub])

# print result
print("The total element product in lists is : " + str(res))


The original list : [[1, 4, 5], [7, 3], [4], [46, 7, 3]]
The total element product in lists is : 1622880


**Transpose a matrix in Single line in Python**

In [ ]:
import numpy
matrix = [[1, 2, 3], [4, 5, 6]]
print(matrix)
print("\n")
print(numpy.transpose(matrix))


[[1, 2, 3], [4, 5, 6]]


[[1 4]
 [2 5]
 [3 6]]


Matrix creation of n*n **bold text**

In [ ]:
# Python3 code to demonstrate
# matrix creation of n * n
# using list comprehension

# initializing N
N = 4

# printing dimension
print("The dimension : " + str(N))

# using list comprehension
# matrix creation of n * n
res = [list(range(1 + N * i, 1 + N * (i + 1)))
							for i in range(N)]

# print result
print("The created matrix of N * N: " + str(res))


The dimension : 4
The created matrix of N * N: [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]


https://www.javatpoint.com/python-bitwise-operators

**Numpy | Binary Operations**
Binary operators acts on bits and performs bit by bit operation. Binary operation is simply a rule for combining two values to create a new value.

In [ ]:
# Python program explaining
# bitwise_and() function

import numpy as g
in_num1 = 10
in_num2 = 11

print ("Input  number1 : ", in_num1)
print ("Input  number2 : ", in_num2)

out_num = g.bitwise_and(in_num1, in_num2)
print ("bitwise_and of 10 and 11 : ", out_num)


Input  number1 :  10
Input  number2 :  11
bitwise_and of 10 and 11 :  10


In [ ]:
# Python program explaining
# bitwise_and() function

import numpy as g
in_num1 = 10
in_num2 = 11

print ("Input  number1 : ", in_num1)
print ("Input  number2 : ", in_num2)

out_num = g.bitwise_and(in_num1, in_num2)
print ("bitwise_and of 10 and 11 : ", out_num)


In [ ]:
# Python program explaining
# bitwise_or() function

import numpy as g
in_num1 = 10
in_num2 = 11

print ("Input  number1 : ", in_num1)
print ("Input  number2 : ", in_num2)

out_num = g.bitwise_or(in_num1, in_num2)
print ("bitwise_or of 10 and 11 : ", out_num)


Input  number1 :  10
Input  number2 :  11
bitwise_or of 10 and 11 :  11


**Numpy | Mathematical Function**
FUNCTION	DESCRIPTION
tan()	Compute tangent element-wise.
arcsin()	Inverse sine, element-wise.
arccos()	Trigonometric inverse cosine, element-wise.
arctan()	Trigonometric inverse tangent, element-wise.
arctan2()	Element-wise arc tangent of x1/x2 choosing the quadrant correctly.
degrees()	Convert angles from radians to degrees.
rad2deg()	Convert angles from radians to degrees.
deg2rad	Convert angles from degrees to radians.
radians()	Convert angles from degrees to radians.
hypot()	Given the “legs” of a right triangle, return its hypotenuse.
unwrap()	Unwrap by changing deltas between values to 2*pi complement
rint()	Round to nearest integer towards zero.
fix()	Round to nearest integer towards zero.
floor()	Return the floor of the input, element-wise.
ceil()	Return the ceiling of the input, element-wise.
trunc()	Return the truncated value of the input, element-wise.
https://www.javatpoint.com/numpy-mathematical-functions

**Numpy | String Operations**
numpy.lower() : This function returns the lowercase string from the given string. It converts all uppercase characters to lowercase. If no uppercase characters exist, it returns the original string.

In [ ]:
# Python program explaining
# numpy.lower() function

import numpy as np

# converting to lowercase
print(np.char.lower(['SAURABH', 'FOR']))

# converting to lowercase
print(np.char.lower('SAURABH'))


['saurabh' 'for']
saurabh


In [ ]:
 # numpy.split() function

import numpy as np

# splitting a string
print(np.char.split('Hero for India'))

# splitting a string
print(np.char.split('Hero, for, India', sep = ':'))

['Hero', 'for', 'India']
['Hero, for, India']


In [ ]:
# numpy.join() function

import numpy as np

# splitting a string
print(np.char.join('-', 'Sachin'))

# splitting a string
print(np.char.join(['-', ':'], ['Sachin', 'for']))

S-a-c-h-i-n
['S-a-c-h-i-n' 'f:o:r']


https://www.javatpoint.com/numpy-string-functions

**Reshape NumPy Array**

In [ ]:
# importing numpy
import numpy as np

# creating a numpy array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])

# printing array
print("Array : " + str(array))


# reshaping numpy array
# converting it to 3-D from 1-D array
reshaped = array.reshape((2, 2, 4))

# printing reshaped array
print("Reshaped 3-D Array : ")
print(reshaped)


In [ ]:
# importing numpy
import numpy as np

# creating a numpy array
array = np.array([[1, 2, 3],
				[4, 5, 6],
				[7, 8, 9]])

# printing array
print(" 2-D Array : ")
print(array)


# reshaping numpy array
# converting it to 1-D from 2-D array
reshaped = array.reshape((9))

# or we can use unknown dimension
# reshaped = array.reshape((-1))

# printing reshaped array
print("Reshaped 1-D Array : ")
print(reshaped)


#                                                  **PANDAS**

Pandas is well-suited for working with tabular data, such as spreadsheets or SQL tables. The Pandas library is an essential tool for data analysts, scientists, and engineers working with




In [ ]:
import pandas as pd
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


DataFrame can be created using a single list or a list of lists.

In [ ]:
import pandas as pd
lst = ['We', 'are', 'here','for','Global', 'Logic']
df = pd.DataFrame(lst)
print(df)

        0
0      We
1     are
2    here
3     for
4  Global
5   Logic


To create DataFrame from dict of narray/list, all the narray must be of same length. If index is passed then the length index should be equal to the length of arrays. If no index is passed, then by default, index will be range(n) where n is the array length.

In [ ]:
import pandas as pd
data = {'Name':['A', 'B', 'C', 'D'], 'Age':[20, 21, 19, 18]}
df = pd.DataFrame(data)
print(df)


  Name  Age
0    A   20
1    B   21
2    C   19
3    D   18


Creating pandas data-frame from lists using dictionary can be achieved in different ways. We can create pandas dataframe from lists using dictionary using pandas.DataFrame. With this method in Pandas we can transform a dictionary of list to a dataframe.

In [ ]:
import pandas as pd
dict = {'name':["A", "B", "C", "D"],
		'degree': ["MBA", "BCA", "M.Tech", "MBA"],
		'score':[90, 40, 80, 98]}
df = pd.DataFrame(dict)
print(df)


  name  degree  score
0    A     MBA     90
1    B     BCA     40
2    C  M.Tech     80
3    D     MBA     98


Pandas Series is a one-dimensional labeled array capable of holding data of any type (integer, string, float, python objects, etc.). The axis labels are collectively called index. Labels need not be unique but must be a hashable type. The object supports both integer and label-based indexing and provides a host of methods for performing operations involving the index.

**Creating an empty Series:** Series() function of Pandas is used to create a series. A basic series, which can be created is an Empty Series.



In [ ]:
import pandas as pd
s = pd.Series()
print(s)


Series([], dtype: object)


**Creating a series from array:** In order to create a series from NumPy array, we have to import numpy module and have to use array() function.

In [ ]:
import pandas as pd
import numpy as np
data = np.array(['G', 'l', 'o', 'b', 'a','l','L','o','g','i','c'])
ser = pd.Series(data)
print(ser)

0     G
1     l
2     o
3     b
4     a
5     l
6     L
7     o
8     g
9     i
10    c
dtype: object


**Creating a series from array with an index:** In order to create a series by explicitly proving index instead of the default, we have to provide a list of elements to the index parameter with the same number of elements as it is an array.

In [ ]:
import pandas as pd
import numpy as np
data = np.array(['p', 'a', 'n', 'd', 'a','s'])
s = pd.Series(data, index=[10, 11, 12, 13, 14, 15])
print(s)

10    p
11    a
12    n
13    d
14    a
15    s
dtype: object


**Creating a series from Scalar value:** In order to create a series from scalar value, an index must be provided. The scalar value will be repeated to match the length of the index.

In [ ]:
import pandas as pd
import numpy as np
s = pd.Series(10, index=[0, 1, 2, 3, 4, 5])
print(s)

0    10
1    10
2    10
3    10
4    10
5    10
dtype: int64


**Creating a series using NumPy functions :** In order to create a series using numpy function, we can use different function of numpy like numpy.linspace(), numpy.random.radn().
The numpy.random.randn() function creates an array of specified shape and fills it with random values as per standard normal distribution.
If positive arguments are provided, randn generates an array of shape (d0, d1, …, dn), filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1 (if any of the d_i are floats, they are first converted to integers by truncation). A single float randomly sampled from the distribution is returned if no argument is provided.

In [ ]:
import pandas as pd
import numpy as np
s1 = pd.Series(np.linspace(3, 33, 3))
print(s1)
s2 = pd.Series(np.linspace(1, 100, 10))
print("\n"	 , s2)


0     3.0
1    18.0
2    33.0
dtype: float64

 0      1.0
1     12.0
2     23.0
3     34.0
4     45.0
5     56.0
6     67.0
7     78.0
8     89.0
9    100.0
dtype: float64


In [ ]:
import numpy as geek
array = geek.random.randn(5)
print("1D Array filled with random values : \n", array);


1D Array filled with random values : 
 [ 0.22939246 -1.2132165  -0.75882044  2.13958332 -0.78271703]


Python is a great language for doing data analysis, primarily because of the fantastic ecosystem of data-centric Python packages. Pandas is one of those packages and makes importing and analyzing data much easier.

Pandas head() method is used to return top n (5 by default) rows of a data frame or series.

In [ ]:
import pandas as pd
data = pd.read_csv("/nba.csv")
data_top = data.head()
data_top


Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   

             College     Salary  
0              Texas  7730337.0  
1          Marquette  6796117.0  
2  Boston University        NaN  
3      Georgia State  1148640.0  
4                NaN  5000000.0

In this example, the .head() method is called on series with custom input of n parameter to return top 9 rows of the series.


In [ ]:
import pandas as pd
data = pd.read_csv("/nba.csv")
n = 9
series = data["Name"]
top = series.head(n = n)
top

0    Avery Bradley
1      Jae Crowder
2     John Holland
3      R.J. Hunter
4    Jonas Jerebko
5     Amir Johnson
6    Jordan Mickey
7     Kelly Olynyk
8     Terry Rozier
Name: Name, dtype: object

Pandas tail() method is used to return bottom n (5 by default) rows of a data frame or series.

In [ ]:
import pandas as pd
data = pd.read_csv("/nba.csv")
data_bottom = data.tail()
data_bottom

Name       Team  Number Position   Age Height  Weight College  \
453  Shelvin Mack  Utah Jazz     8.0       PG  26.0    6-3   203.0  Butler   
454     Raul Neto  Utah Jazz    25.0       PG  24.0    6-1   179.0     NaN   
455  Tibor Pleiss  Utah Jazz    21.0        C  26.0    7-3   256.0     NaN   
456   Jeff Withey  Utah Jazz    24.0        C  26.0    7-0   231.0  Kansas   
457           NaN        NaN     NaN      NaN   NaN    NaN     NaN     NaN   

        Salary  
453  2433333.0  
454   900000.0  
455  2900000.0  
456   947276.0  
457        NaN

In [ ]:
import pandas as pd
data = pd.read_csv("/nba.csv")
n=10
data_bottom = data.tail(n=n)
data_bottom

Name       Team  Number Position   Age Height  Weight  \
448  Gordon Hayward  Utah Jazz    20.0       SF  26.0    6-8   226.0   
449     Rodney Hood  Utah Jazz     5.0       SG  23.0    6-8   206.0   
450      Joe Ingles  Utah Jazz     2.0       SF  28.0    6-8   226.0   
451   Chris Johnson  Utah Jazz    23.0       SF  26.0    6-6   206.0   
452      Trey Lyles  Utah Jazz    41.0       PF  20.0   6-10   234.0   
453    Shelvin Mack  Utah Jazz     8.0       PG  26.0    6-3   203.0   
454       Raul Neto  Utah Jazz    25.0       PG  24.0    6-1   179.0   
455    Tibor Pleiss  Utah Jazz    21.0        C  26.0    7-3   256.0   
456     Jeff Withey  Utah Jazz    24.0        C  26.0    7-0   231.0   
457             NaN        NaN     NaN      NaN   NaN    NaN     NaN   

      College      Salary  
448    Butler  15409570.0  
449      Duke   1348440.0  
450       NaN   2050000.0  
451    Dayton    981348.0  
452  Kentucky   2239800.0  
453    Butler   2433333.0  
454       NaN    900000.0  
455       NaN   2900000.0  
456    Kansas    947276.0  
457       NaN         NaN

Pandas describe() is used to view some basic statistical details like percentile, mean, std, etc. of a data frame or a series of numeric values. When this method is applied to a series of strings, it returns a different output which is shown in the examples below.

In [ ]:
import pandas as pd
data = pd.read_csv('nba.csv')
print(data.head())

            Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   

             College     Salary  
0              Texas  7730337.0  
1          Marquette  6796117.0  
2  Boston University        NaN  
3      Georgia State  1148640.0  
4                NaN  5000000.0  


We can easily learn about several statistical measures, including mean, median, standard deviation, quartiles, and more, by using describe() on a DataFrame.

In [ ]:
print(data.describe())

           Number         Age      Weight        Salary
count  457.000000  457.000000  457.000000  4.460000e+02
mean    17.678337   26.938731  221.522976  4.842684e+06
std     15.966090    4.404016   26.368343  5.229238e+06
min      0.000000   19.000000  161.000000  3.088800e+04
25%      5.000000   24.000000  200.000000  1.044792e+06
50%     13.000000   26.000000  220.000000  2.839073e+06
75%     25.000000   30.000000  240.000000  6.500000e+06
max     99.000000   40.000000  307.000000  2.500000e+07


**Indexing in Pandas :**Indexing in pandas means simply selecting particular rows and columns of data from a DataFrame. Indexing could mean selecting all the rows and some of the columns, some of the rows and all of the columns, or some of each of the rows and columns. Indexing can also be known as Subset Selection

Pandas Indexing using [ ], .loc[], .iloc[ ], .ix[ ]
There are a lot of ways to pull the elements, rows, and columns from a DataFrame. There are some indexing method in Pandas which help in getting an element from a DataFrame. These indexing methods appear very similar but behave very differently. Pandas support four types of Multi-axes indexing they are:

**Dataframe.[ ] :** This function also known as indexing operator
**Dataframe.loc[ ] :** This function is used for labels.
**Dataframe.iloc[ ] :** This function is used for positions or integer based
**Dataframe.ix[] :** This function is used for both label and integer based
Collectively, they are called the **indexers**

**.loc[ ]:** This function selects data by the label of the rows and columns. The df.loc indexer selects data in a different way than just the indexing operator. It can select subsets of rows or columns. It can also simultaneously select subsets of rows and columns.Selecting a single row in order to select a single row using .loc[], we put a single row label in a .loc function.

In [ ]:
import pandas as pd
data = pd.read_csv("nba.csv", index_col ="Name")
first = data.loc["Avery Bradley"]
second = data.loc["R.J. Hunter"]
print(first, "\n\n\n", second)

Team        Boston Celtics
Number                 0.0
Position                PG
Age                   25.0
Height                 6-2
Weight               180.0
College              Texas
Salary           7730337.0
Name: Avery Bradley, dtype: object 


 Team        Boston Celtics
Number                28.0
Position                SG
Age                   22.0
Height                 6-5
Weight               185.0
College      Georgia State
Salary           1148640.0
Name: R.J. Hunter, dtype: object


**Selecting two rows and three columns:** In order to select two rows and three columns, we select a two rows which we want to select and three columns and put it in a separate list like this:

**Dataframe.loc[["row1", "row2"], ["column1", "column2", "column3"]]**

In [ ]:
import pandas as pd
data = pd.read_csv("nba.csv", index_col ="Name")
first = data.loc[["Avery Bradley", "R.J. Hunter"],
                   ["Team", "Number", "Position"]]
print(first)

                         Team  Number Position
Name                                          
Avery Bradley  Boston Celtics     0.0       PG
R.J. Hunter    Boston Celtics    28.0       SG


**Selecting all of the rows and some columns:**
In order to select all of the rows and some columns, we use single colon [:]
to select all of rows and list of some columns which we want to select like this:
**Dataframe.loc[:, ["column1", "column2", "column3"]]**

In [ ]:
import pandas as pd
data = pd.read_csv("nba.csv", index_col ="Name")
first = data.loc[:, ["Team", "Number", "Position"]]
print(first)

                         Team  Number Position
Name                                          
Avery Bradley  Boston Celtics     0.0       PG
Jae Crowder    Boston Celtics    99.0       SF
John Holland   Boston Celtics    30.0       SG
R.J. Hunter    Boston Celtics    28.0       SG
Jonas Jerebko  Boston Celtics     8.0       PF
...                       ...     ...      ...
Shelvin Mack        Utah Jazz     8.0       PG
Raul Neto           Utah Jazz    25.0       PG
Tibor Pleiss        Utah Jazz    21.0        C
Jeff Withey         Utah Jazz    24.0        C
NaN                       NaN     NaN      NaN

[458 rows x 3 columns]


**Indexing a DataFrame using .iloc[ ]:** This function allows us to retrieve rows and columns by position. In order to do that, we’ll need to specify the positions of the rows that we want, and the positions of the columns that we want as well. The df.iloc[] indexer is very similar to df.loc but only uses integer locations to make its selections. Selecting a single row In order to select a single row using .iloc[], we can pass a single integer to.iloc[]
function.

In [ ]:
import pandas as pd
data = pd.read_csv("nba.csv", index_col ="Name")
row2 = data.iloc[3]
print(row2)

Team        Boston Celtics
Number                28.0
Position                SG
Age                   22.0
Height                 6-5
Weight               185.0
College      Georgia State
Salary           1148640.0
Name: R.J. Hunter, dtype: object


In [ ]:
import pandas as pd
data = pd.read_csv("nba.csv", index_col ="Name")
row2 = data.iloc [[3, 5, 7]]
row2

Team  Number Position   Age Height  Weight  \
Name                                                                 
R.J. Hunter   Boston Celtics    28.0       SG  22.0    6-5   185.0   
Amir Johnson  Boston Celtics    90.0       PF  29.0    6-9   240.0   
Kelly Olynyk  Boston Celtics    41.0        C  25.0    7-0   238.0   

                    College      Salary  
Name                                     
R.J. Hunter   Georgia State   1148640.0  
Amir Johnson            NaN  12000000.0  
Kelly Olynyk        Gonzaga   2165160.0

Pandas str.slice() method is used to slice substrings from a string present in Pandas series object. It is very similar to Python’s basic principal of slicing objects that works on [start:stop:step] which means it requires three parameters, where to start, where to end and how much elements to skip.
Since this is a pandas string method, .str has to be prefixed every time before calling this method. Otherwise, it gives an error.

In this example, the salary column has been sliced to get values before decimal. For example, we want to do some mathematical operations and for that we need integer data, so the salary column will be sliced till the 2nd last element(-2 position).
Since the salary column is imported as float64 data type, it is first converted to string using the .astype() method.

In [1]:
import pandas as pd
data = pd.read_csv("/nba.csv")
data.dropna(inplace = True)
start, stop, step = 0, -2, 1
data["Salary"]= data["Salary"].astype(str)
data["Salary (int)"]= data["Salary"].str.slice(start, stop, step)
data.head(10)
type(data)

FileNotFoundError: [Errno 2] No such file or directory: '/nba.csv'

Pandas Series.apply() function invoke the passed function on each element of the given series object.

In [ ]:
import pandas as pd
sr = pd.Series(['New York', 'Chicago', 'Toronto', 'Lisbon', 'Rio'])
index_ = ['City 1', 'City 2', 'City 3', 'City 4', 'City 5']
sr.index = index_
print(sr)


City 1    New York
City 2     Chicago
City 3     Toronto
City 4      Lisbon
City 5         Rio
dtype: object


Dataframe.aggregate() function is used to apply some aggregation across one or more columns. Aggregate using callable, string, dict, or list of string/callables. The most frequently used aggregations are:

**sum: Return the sum of the values for the requested axis**

**min: Return the minimum of the values for the requested axis**

**max: Return the maximum of the values for the requested axis**

In [ ]:
import pandas as pd
data = pd.read_csv("/content/nba.csv")
data.aggregate({"Number":['sum', 'min'],
              "Age":['max', 'min'],
              "Weight":['min', 'sum'],
              "Salary":['sum']})



Number   Age    Weight        Salary
sum  8079.0   NaN  101236.0  2.159837e+09
min     0.0  19.0     161.0           NaN
max     NaN  40.0       NaN           NaN

Use mean() function to find the mean of all the observations over the index axis.

In [ ]:
import pandas as pd
df = pd.DataFrame({"A":[12, 4, 5, 44, 1],
                "B":[5, 2, 54, 3, 2],
                "C":[20, 16, 7, 3, 8],
                "D":[14, 3, 17, 2, 6]})
df


A   B   C   D
0  12   5  20  14
1   4   2  16   3
2   5  54   7  17
3  44   3   3   2
4   1   2   8   6

Pandas dataframe.mad() function return the mean absolute deviation of the values for the requested axis. The mean absolute deviation of a dataset is the average distance between each data point and the mean. It gives us an idea about the variability in a dataset.

In [ ]:
import pandas as pd
df = pd.DataFrame({"A":[12, 4, 5, 44, 1],
				"B":[5, 2, 54, 3, 2],
				"C":[20, 16, 7, 3, 8],
				"D":[14, 3, 17, 2, 6]})
df


A   B   C   D
0  12   5  20  14
1   4   2  16   3
2   5  54   7  17
3  44   3   3   2
4   1   2   8   6

**Add a New Column to an Existing Datframe using DataFrame insert()**
It gives the freedom to add a column at any position we like and not just at the end. It also provides different options for inserting the column values.

In [ ]:
import pandas as pd
data = {'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc']}
df = pd.DataFrame(data)
df.insert(2, "Age", [21, 23, 24, 21], True)
print(df)

     Name  Height  Age Qualification
0     Jai     5.1   21           Msc
1  Princi     6.2   23            MA
2  Gaurav     5.1   24           Msc
3    Anuj     5.2   21           Msc


**Adding Columns to Pandas DataFrame using Dataframe.assign()**
This method will create a new dataframe with a new column added to the old dataframe.

In [ ]:
import pandas as pd
data = {'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc']}
df = pd.DataFrame(data)
df2 = df.assign(address=['Delhi', 'Bangalore', 'Chennai', 'Patna'])
print(df2)

     Name  Height Qualification    address
0     Jai     5.1           Msc      Delhi
1  Princi     6.2            MA  Bangalore
2  Gaurav     5.1           Msc    Chennai
3    Anuj     5.2           Msc      Patna


Groupby is a pretty simple concept. We can create a grouping of categories and apply a function to the categories. It’s a simple concept but it’s an extremely valuable technique that’s widely used in data science. In real data science projects, you’ll be dealing with large amounts of data and trying things over and over, so for efficiency, we use Groupby concept. Groupby concept is really important because it’s ability to aggregate data efficiently, both in performance and the amount code is magnificent. Groupby mainly refers to a process involving one or more of the following steps they are:

 **Splitting :** It is a process in which we split data into group by applying some conditions on datasets.
**Applying :** It is a process in which we apply a function to each group independently

**Combining :** It is a process in which we combine different datasets after applying groupby and results into a data structure

In [ ]:
import pandas as pd
data1 = {'Name':['Jai', 'Anuj', 'Jai', 'Princi',
				'Gaurav', 'Anuj', 'Princi', 'Abhi'],
		'Age':[27, 24, 22, 32,
			33, 36, 27, 32],
		'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj',
				'Jaunpur', 'Kanpur', 'Allahabad', 'Aligarh'],
		'Qualification':['Msc', 'MA', 'MCA', 'Phd',
						'B.Tech', 'B.com', 'Msc', 'MA']}
df = pd.DataFrame(data1)
df.groupby('Name')
print(df.groupby('Name').groups)

{'Abhi': [7], 'Anuj': [1, 5], 'Gaurav': [4], 'Jai': [0, 2], 'Princi': [3, 6]}


For grouping rows in Pandas, we will start with creating a pandas dataframe first.

In [ ]:
import pandas as pd
example = {'Team':['Arsenal', 'Manchester United', 'Arsenal',
				'Arsenal', 'Chelsea', 'Manchester United',
				'Manchester United', 'Chelsea', 'Chelsea', 'Chelsea'],
					'Player':['Ozil', 'Pogba', 'Lucas', 'Aubameyang',
					'Hazard', 'Mata', 'Lukaku', 'Morata',
										'Giroud', 'Kante'],
					'Goals':[5, 3, 6, 4, 9, 2, 0, 5, 2, 3] }
df = pd.DataFrame(example)
total_goals = df['Goals'].groupby(df['Team'])
print(total_goals.mean())

Team
Arsenal              5.000000
Chelsea              4.750000
Manchester United    1.666667
Name: Goals, dtype: float64


combine multiple columns in Pandas using groupby with dictionary with the help of different examples.

In [ ]:
import pandas as pd
d = {'id':['1', '2', '3'],
	'Column 1.1':[14, 15, 16],
	'Column 1.2':[10, 10, 10],
	'Column 1.3':[1, 4, 5],
	'Column 2.1':[1, 2, 3],
	'Column 2.2':[10, 10, 10], }
df = pd.DataFrame(d)
groupby_dict = {'Column 1.1':'Column 1',
				'Column 1.2':'Column 1',
				'Column 1.3':'Column 1',
				'Column 2.1':'Column 2',
				'Column 2.2':'Column 2' }
df = df.set_index('id')
df = df.groupby(groupby_dict, axis = 1).min()
print(df)

    Column 1  Column 2
id                    
1          1         1
2          4         2
3          5         3


 It is possible to compare two pandas Series with help of Relational operators, we can easily compare the corresponding elements of two series at a time.

Checking if two Series elements are equal or not

In [ ]:
import pandas as pd
ps1 = pd.Series([2.5, 4, 6, 8, 10, 1.75, 40])
ps2 = pd.Series([1.5, 3, 5, 7, 10, 1.75, 20])
print("Series1:")
print(ps1)
print("\nSeries2:")
print(ps2)
print("\nCompare the elements of the two given Series:")
print("\nEqual:")
print(ps1 == ps2)
print("\nNot Equal:")
print(ps1 != ps2)


Series1:
0     2.50
1     4.00
2     6.00
3     8.00
4    10.00
5     1.75
6    40.00
dtype: float64

Series2:
0     1.50
1     3.00
2     5.00
3     7.00
4    10.00
5     1.75
6    20.00
dtype: float64

Compare the elements of the two given Series:

Equal:
0    False
1    False
2    False
3    False
4     True
5     True
6    False
dtype: bool

Not Equal:
0     True
1     True
2     True
3     True
4    False
5    False
6     True
dtype: bool


Pandas str.cat() is used to concatenate strings to the passed caller series of string. Distinct values from a different series can be passed but the length of both the series has to be same. .str has to be prefixed to differentiate it from the Python’s default method.

In [ ]:
import pandas as pd
data = pd.read_csv("/content/nba.csv")
new = data["Team"].copy()
data["Name"]= data["Name"].str.cat(new, sep =", ")
data


Name            Team  Number Position   Age  \
0    Avery Bradley, Boston Celtics  Boston Celtics     0.0       PG  25.0   
1      Jae Crowder, Boston Celtics  Boston Celtics    99.0       SF  25.0   
2     John Holland, Boston Celtics  Boston Celtics    30.0       SG  27.0   
3      R.J. Hunter, Boston Celtics  Boston Celtics    28.0       SG  22.0   
4    Jonas Jerebko, Boston Celtics  Boston Celtics     8.0       PF  29.0   
..                             ...             ...     ...      ...   ...   
453        Shelvin Mack, Utah Jazz       Utah Jazz     8.0       PG  26.0   
454           Raul Neto, Utah Jazz       Utah Jazz    25.0       PG  24.0   
455        Tibor Pleiss, Utah Jazz       Utah Jazz    21.0        C  26.0   
456         Jeff Withey, Utah Jazz       Utah Jazz    24.0        C  26.0   
457                            NaN             NaN     NaN      NaN   NaN   

    Height  Weight            College     Salary  
0      6-2   180.0              Texas  7730337.0  
1      6-6   235.0          Marquette  6796117.0  
2      6-5   205.0  Boston University        NaN  
3      6-5   185.0      Georgia State  1148640.0  
4     6-10   231.0                NaN  5000000.0  
..     ...     ...                ...        ...  
453    6-3   203.0             Butler  2433333.0  
454    6-1   179.0                NaN   900000.0  
455    7-3   256.0                NaN  2900000.0  
456    7-0   231.0             Kansas   947276.0  
457    NaN     NaN                NaN        NaN  

[458 rows x 9 columns]