**Reshape the 1-D array of shape (1, n) to 2-D array of shape (N, M) here M should be equal to the n/N there for N should be factor of n. **

In [7]:
# importing numpy
import numpy as np

# creating a numpy array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])

# printing array
print("Array : " + str(array))

# length of array
n = array.size

# N-D array N dimension
N = 4

# calculating M
M = n//N

# reshaping numpy array
# converting it to 2-D from 1-D array
reshaped1 = array.reshape((N, M))

# printing reshaped array
print("First Reshaped Array : ")
print(reshaped1)

# creating another reshaped array
reshaped2 = np.reshape(array, (2, 8))

# printing reshaped array
print("Second Reshaped Array : ")
print(reshaped2)


Array : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
First Reshaped Array : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Second Reshaped Array : 
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


**Reshaping : 1-D to 3-D **
In this we will see how we can reshape a 1-D array to 3-D dimension array. A 3-D array is the 1-D array of 2-D arrays

In [8]:
# importing numpy
import numpy as np

# creating a numpy array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])

# printing array
print("Array : " + str(array))


# reshaping numpy array
# converting it to 3-D from 1-D array
reshaped = array.reshape((2, 2, 4))

# printing reshaped array
print("Reshaped 3-D Array : ")
print(reshaped)


Array : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
Reshaped 3-D Array : 
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


**Reshaping N-D to 1-D array **
In this example we will see how we can reshape a 2-D or 3-D array to form a 1-D array. We can also use reshape(-1) to do this, here -1 is the unknown dimension.

In [9]:
# importing numpy
import numpy as np

# creating a numpy array
array = np.array([[1, 2, 3],
				[4, 5, 6],
				[7, 8, 9]])

# printing array
print(" 2-D Array : ")
print(array)


# reshaping numpy array
# converting it to 1-D from 2-D array
reshaped = array.reshape((9))

# or we can use unknown dimension
# reshaped = array.reshape((-1))

# printing reshaped array
print("Reshaped 1-D Array : ")
print(reshaped)


 2-D Array : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped 1-D Array : 
[1 2 3 4 5 6 7 8 9]



**Reshaping using unknown dimension **
We can reshape a array although we don’t know all the new dimensions by using -1 as one of the dimension, but we should know all the other dimension to use unknown dimension


In [10]:
# importing numpy
import numpy as np

# creating a numpy array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])

# printing array
print("Array : " + str(array))


# reshaping numpy array
# converting it to 3-D from 1-D array
reshaped1 = array.reshape((2, 2, -1))

# printing reshaped array
print("First Reshaped Array : ")
print(reshaped1)


# converting it to 2-D array
reshaped2 = array.reshape((4, -1))

# printing reshaped array
print("Second Reshaped Array : ")
print(reshaped2)


Array : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
First Reshaped Array : 
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
Second Reshaped Array : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


**Basic Slicing and Advanced Indexing in NumPy**
Indexing can be done in NumPy by using an array as an index.

Numpy arrays can be indexed with other arrays or any other sequence with the exception of tuples. The last element is indexed by -1 second last by -2 and so on.

In [11]:
import numpy as np
# Create a sequence of integers from 10 to 1 with a step of -2
a = np.arange(10, 1, -2)
print("\n A sequential array with a negative step: \n",a)
# Indexes are specified inside the np.array method.
newarr = a[np.array([3, 1, 2 ])]
print("\n Elements at these indices are:\n",newarr)



 A sequential array with a negative step: 
 [10  8  6  4  2]

 Elements at these indices are:
 [4 8 6]


**Basic Slicing and indexing**
Basic slicing and indexing is used to access a specific element or range of elements from a NumPy array.

Basic slicing and indexing only return the view of the array.

Consider the syntax x[obj] where “x” is the array and “obj” is the index. The slice object is the index in the case of basic slicing.

Basic slicing occurs when obj is :

A slice object that is of the form start: stop: step

An integer
Or a tuple of slice objects and integers

In [12]:
import numpy as np
# Arrange elements from 0 to 19
a = np.arange(20)
print("\n Array is:\n ",a)
print("\n a[15]=",a[15])
# a[start:stop:step]
print("\n a[-8:17:1] = ",a[-8:17:1])
print("\n a[10:] = ",a[10:])



 Array is:
  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

 a[15]= 15

 a[-8:17:1] =  [12 13 14 15 16]

 a[10:] =  [10 11 12 13 14 15 16 17 18 19]


***Boolean array indexing***

In [13]:
# You may wish to select numbers greater than 50
import numpy as np

a = np.array([10, 40, 80, 50, 100])
print(a[a>50])


[ 80 100]


In [14]:
#Example 2: Using boolean indexing on NumPy array to find numbers whose sum row is 10
# You may wish to select those elements whose
# sum of row is a multiple of 10.
import numpy as np

b = np.array([[5, 5],[4, 5],[16, 4]])
sumrow = b.sum(-1)
print(b[sumrow%10==0])


[[ 5  5]
 [16  4]]


**NumPy Array Broadcasting**
The term broadcasting refers to the ability of NumPy to treat arrays with different dimensions during arithmetic operations. This process involves certain rules that allow the smaller array to be ‘broadcast’ across the larger one, ensuring that they have compatible shapes for these operations.

In [15]:
#Broadcasting provides a means of vectorizing array operations, therefore eliminating the need for Python loops.
import numpy as np

a = np.array([5, 7, 3, 1])
b = np.array([90, 50, 0, 30])

# array are compatible because of same Dimension
c = a * b
print(c)



[450 350   0  30]


In [16]:
macros = array([
[0.8, 2.9, 3.9],
[52.4, 23.6, 36.5],
[55.2, 31.7, 23.9],
[14.4, 11, 4.9]
])

result = zeros_like(macros)

cal_per_macro = array([3, 3, 8])

for i in range(macros.shape[0]):
	result[i, :] = macros[i, :] * cal_per_macro

result


TypeError: 'numpy.ndarray' object is not callable

**Estimation of Variable**----
**Variability**: It is the import dimension that measures the data variation i.e. whether the data is spread out or tightly clustered. Also known as Dispersion

Terms related to Variability Metrics :
-> Deviation
-> Variance
-> Standard Deviation
-> Mean Absolute Deviation
-> Median Absolute Deviation
-> Order Statistics
-> Range
-> Percentile
-> Inter-quartile Range

In [ ]:
#Deviation: We can call it – errors or residuals also. It is the measure of how different/dispersed the values are, from the central/observed value.
Sequence : [2, 3, 5, 6, 7, 9]
Mean = 7

Deviation = [-5, -4, -2, -1, 0, 2]

In [ ]:
#Variance (s2): It is the best-known measure to estimate the variability as it is Squared Deviation. One can call it mean squared error as it is the average of standard deviation.

In [ ]:
# Variance

import numpy as np

Sequence = [2, 3, 5, 6, 7, 9]

var = np.var(Sequence)

print("Variance : ", var)


In [ ]:
#Standard Deviation: It is the square root of Variance. Is also referred to as Euclidean Norm.
# Standard Deviation

import numpy as np

Sequence = [2, 3, 5, 6, 7, 9]

std = np.std(Sequence)

print("Standard Deviation : ", std)


In [ ]:
# Mean Absolute Deviation

import numpy as np

def mad(data):
	return np.mean(np.absolute(
			data - np.mean(data)))

Sequence = [2, 4, 6, 8]

print ("Mean Absolute Deviation : ", mad(Sequence))


**Python: Operations on Numpy Arrays**
A Numpy array on a structural level is made up of a combination of:

The Data pointer indicates the memory address of the first byte in the array.
The Data type or dtype pointer describes the kind of elements that are contained within the array.
The shape indicates the shape of the array.
The strides are the number of bytes that should be skipped in memory to go to the next element.

In [ ]:
# Python code to perform arithmetic
# operations on NumPy array


import numpy as np


# Initializing the array
arr1 = np.arange(4, dtype = np.float_).reshape(2, 2)

print('First array:')
print(arr1)

print('\nSecond array:')
arr2 = np.array([12, 12])
print(arr2)

print('\nAdding the two arrays:')
print(np.add(arr1, arr2))

print('\nSubtracting the two arrays:')
print(np.subtract(arr1, arr2))

print('\nMultiplying the two arrays:')
print(np.multiply(arr1, arr2))

print('\nDividing the two arrays:')
print(np.divide(arr1, arr2))


First array:
[[0. 1.]
 [2. 3.]]

Second array:
[12 12]

Adding the two arrays:
[[12. 13.]
 [14. 15.]]

Subtracting the two arrays:
[[-12. -11.]
 [-10.  -9.]]

Multiplying the two arrays:
[[ 0. 12.]
 [24. 36.]]

Dividing the two arrays:
[[0.         0.08333333]
 [0.16666667 0.25      ]]


In [ ]:
#How to use the NumPy sum function ?
# Let's define our function
# Parameters: Input Array
def sum(array):

	# Set variable for our final answer
	sum = 0

	# Parse through our array
	for i in array:

		# Continuously add current element
		# to final sum
		sum += i

	# Return our sum
	return sum


# Create a test array
testArray = [1, 3, 34, 92, 29, 48, 20.3]

# Test our function
print('The sum of your numbers is ' + str(sum(testArray)))


The sum of your numbers is 227.3


In [ ]:
# Import NumPy Library
import numpy as np

# Let's begin with an example array
# Initialize our array
array = [1, 4, 2.5, 3, 7.4, 8]

# Utilize the sum() function
print('The sum of these numbers is ' + str(np.sum(array)))


In [ ]:
# Python program explaining
# divide() function
import numpy as np

# input_array
arr1 = [2, 27, 2, 21, 23]
arr2 = [2, 3, 4, 5, 6]
print ("arr1		 : ", arr1)
print ("arr2		 : ", arr2)

# output_array
out = np.divide(arr1, arr2)
print ("\nOutput array : \n", out)


In [ ]:
#numpy.inner(arr1, arr2): Computes the inner product of two arrays.
# Python Program illustrating
# numpy.inner() method

import numpy as g

# Scalars
product = g.inner(5, 4)
print("inner Product of scalar values : ", product)

# 1D array
vector_a = 2 + 3j
vector_b = 4 + 5j

product = g.inner(vector_a, vector_b)
print("inner Product : ", product)


inner Product of scalar values :  20
inner Product :  (-7+22j)


In [ ]:
#numpy.gcd() in Python Greatest Common Divisor (GCD)
# Python program illustrating
# gcd() method
import numpy as np

arr1 = [120, 24, 42, 10]
arr2 = [2250, 12, 20, 50]

print ("arr1 : ", arr1)
print ("arr2 : ", arr2)

print ("\nGCD of arr1 and arr2 : ", np.gcd(arr1, arr2))
print ("\nGCD of arr1 and 10 : ", np.gcd(arr1, 10))



In [ ]:
#Numpy | Linear Algebra
# Importing numpy as np
import numpy as np

A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])

# Rank of a matrix
print("Rank of A:", np.linalg.matrix_rank(A))

# Trace of matrix A
print("\nTrace of A:", np.trace(A))

# Determinant of a matrix
print("\nDeterminant of A:", np.linalg.det(A))

# Inverse of matrix A
print("\nInverse of A:\n", np.linalg.inv(A))

print("\nMatrix A raised to power 3:\n",
           np.linalg.matrix_power(A, 3))


In [ ]:
# Python Program illustrating
# numpy.dot() method

import numpy as geek

# Scalars
product = geek.dot(5, 4)
print("Dot Product of scalar values  : ", product)

# 1D array
vector_a = 2 + 3j
vector_b = 4 + 5j

product = geek.dot(vector_a, vector_b)
print("Dot Product  : ", product)


https://www.javatpoint.com/numpy-linear-algebra

**umPy Universal functions** (ufuncs in short) are simple mathematical functions that operate on ndarray (N-dimensional array) in an element-wise fashion.

It supports array broadcasting, type casting, and several other standard features.

NumPy provides various universal functions like standard trigonometric functions, functions for arithmetic operations, handling complex numbers, statistical functions, etc.

ufunc’s Trigonometric Functions in NumPy

Function	Description
sin, cos, tan	compute the sine, cosine, and tangent of angles
arcsin, arccos, arctan	calculate inverse sine, cosine, and tangent
hypot	calculate the hypotenuse of the given right triangle
sinh, cosh, tanh	compute hyperbolic sine, cosine, and tangent
arcsinh, arccosh, arctanh	compute inverse hyperbolic sine, cosine, and tangent
deg2rad	convert degree into radians
rad2deg	convert radians into degree

In [ ]:
# Python code to demonstrate trigonometric function
import numpy as np

# create an array of angles
angles = np.array([0, 30, 45, 60, 90, 180])

# conversion of degree into radians
# using deg2rad function
radians = np.deg2rad(angles)

# sine of angles
print('Sine of angles in the array:')
sine_value = np.sin(radians)
print(np.sin(radians))

# inverse sine of sine values
print('Inverse Sine of sine values:')
print(np.rad2deg(np.arcsin(sine_value)))

# hyperbolic sine of angles
print('Sine hyperbolic of angles in the array:')
sineh_value = np.sinh(radians)
print(np.sinh(radians))

# inverse sine hyperbolic
print('Inverse Sine hyperbolic:')
print(np.sin(sineh_value))

# hypot function demonstration
base = 4
height = 3
print('hypotenuse of right triangle is:')
print(np.hypot(base, height))


**Create your own universal function in NumPy**
Below are the ways by which we can create our universal function in NumPy:

Using frompyfunc() Function

Using numpy.vectorize() Function

In [ ]:
# using numpy
import numpy as np

# creating own function
def fxn(val):
      return(val % 2)

# adding into numpy
mod_2 = np.frompyfunc(fxn, 1, 1)

# creating numpy array
arr = np.arange(1, 11)
print("arr	 :", *arr)

# using function over numpy array
mod_arr = mod_2(arr)
print("mod_arr :", *mod_arr)


arr	 : 1 2 3 4 5 6 7 8 9 10
mod_arr : 1 0 1 0 1 0 1 0 1 0


In [ ]:
#Create Own Universal Function Using np.vectorize() Function
import numpy as np

def circle_area(radius):
	return np.pi * radius**2

# Create a vectorized version of the function
circle_ufunc = np.vectorize(circle_area)

# Test the ufunc with a single value
radius_values = np.array([1, 2, 3, 4])
areas = circle_ufunc(radius_values)
print(areas)


[ 3.14159265 12.56637061 28.27433388 50.26548246]


***Searching in a NumPy array***

Numpy provides various methods for searching different kinds of numerical values, in this article, we will cover two important ones.

numpy.where()

numpy.searchsorted()

In [ ]:
# numpy.where:() It returns the indices of elements in an input array where the given condition is satisfied.
# importing the module
import numpy as np

# creating the array
arr = np.array([10, 32, 30, 50, 20, 82, 91, 45])

# printing arr
print("arr = {}".format(arr))

# looking for value 30 in arr and storing its index in i
i = np.where(arr == 30)
print("i = {}".format(i))


arr = [10 32 30 50 20 82 91 45]
i = (array([2]),)


In [ ]:
#numpy.searchsorted(): The function is used to find the indices into a sorted array arr such that, if elements are inserted before the indices, the order of arr would be still preserved.
#Here, a binary search is used to find the required insertion indices.
# importing the module
import numpy as np

# creating the array
arr = [1, 2, 2, 3, 3, 3, 4, 5, 6, 6]
print("arr = {}".format(arr))

# left-most 3
print("left-most index = {}".format(np.searchsorted(arr, 3, side="left")))

# right-most 3
print("right-most index = {}".format(np.searchsorted(arr, 3, side="right")))


arr = [1, 2, 2, 3, 3, 3, 4, 5, 6, 6]
left-most index = 3
right-most index = 6


**NumPy Array Sorting | How to sort NumPy Array**
You can sort an array in NumPy:

Using np.sort() function

in-line sort

sorting along different axes

Using np.argsort() function

Using np.lexsort() function

In [ ]:
# importing libraries
import numpy as np

a = np.array([12, 15, 10, 1])
print("Array before sorting",a)
a.sort()
print("Array after sorting",a)


In [ ]:
# importing libraries
import numpy as np
# sort along the first axis
a = np.array([[12, 15], [10, 1]])
arr1 = np.sort(a, axis = 0)
print ("Along first axis : \n", arr1)
# sort along the last axis
a = np.array([[10, 15], [12, 1]])
arr2 = np.sort(a, axis = -1)
print ("\nAlong last axis : \n", arr2)
a = np.array([[12, 15], [10, 1]])
arr1 = np.sort(a, axis = None)
print ("\nAlong none axis : \n", arr1)


Along first axis : 
 [[10  1]
 [12 15]]

Along last axis : 
 [[10 15]
 [ 1 12]]

Along none axis : 
 [ 1 10 12 15]


https://www.javatpoint.com/variations-in-different-sorting-techniques-in-python